services:
  # Сервис для Laravel приложения (PHP-FPM)
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petpatterns-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - petpatterns-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Сервис для веб-сервера Nginx
  nginx:
    image: nginx:1.19-alpine
    container_name: petpatterns-nginx
    restart: unless-stopped
    ports:
      - "8890:80" # Пробрасываем порт 8890 с вашего компьютера на порт 80 контейнера
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/app/public:/var/www/public/storage
    depends_on:
      - app
    networks:
      - petpatterns-network

  # Сервис для базы данных MySQL
  db:
    image: mysql:8.0
    container_name: petpatterns-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-petpatterns_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-user}
    volumes:
      - ./docker/db_data:/var/lib/mysql
    ports:
      - "3307:3306" # Пробрасываем порт 3307, чтобы не конфликтовать с локальным MySQL от MAMP
    networks:
      - petpatterns-network

networks:
  petpatterns-network:
    driver: bridge
