name: Build and Push Docker image (production)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set lowercase owner
        id: lcowner
        run: echo "LCOWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image (production)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.LCOWNER }}/petpatterns:${{ env.VERSION }}
            ghcr.io/${{ env.LCOWNER }}/petpatterns:${{ github.sha }}

      - name: Create git tag if not exists
        run: |
          if ! git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag v${{ env.VERSION }}
            git push origin v${{ env.VERSION }}
          fi

      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          tag: v${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image for feature branch
        if: github.ref == 'refs/heads/feature/print-pdf'
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/petpatterns:latest
          docker tag ghcr.io/${{ github.repository_owner }}/petpatterns:latest ghcr.io/${{ github.repository_owner }}/petpatterns:feature-print-pdf
          docker push ghcr.io/${{ github.repository_owner }}/petpatterns:feature-print-pdf 